version: '3'
services:
  metapack:
    image: metapack:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
          CONFIG_FILE: ${CONFIG_FILE}
    env_file:
      - environment-private.env


